### ISSUE TITLE
Fails to rebuild on electron 1.8.8!

### ISSUE THREAD

**Issue by herrjemand** [abandonware/noble#45]
```
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  LIBTOOL-STATIC Release/nothing.a
  CXX(target) Release/obj.target/binding/lib/mac/src/noble_mac.o
In file included from ../lib/mac/src/noble_mac.mm:7:
In file included from ../lib/mac/src/noble_mac.h:3:
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:987:24: error: unknown type name 'napi_async_context'
                       napi_async_context context = nullptr) const;
                       ^
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:990:24: error: unknown type name 'napi_async_context'
                       napi_async_context context = nullptr) const;
                       ^
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:994:24: error: unknown type name 'napi_async_context'
                       napi_async_context context = nullptr) const;
                       ^
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:987:43: error: cannot initialize a parameter of type 'int' with an rvalue of type 'nullptr_t'
                       napi_async_context context = nullptr) const;
                                          ^         ~~~~~~~
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:987:43: note: passing argument to parameter 'context' here
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:990:43: error: cannot initialize a parameter of type 'int' with an rvalue of type 'nullptr_t'
                       napi_async_context context = nullptr) const;
                                          ^         ~~~~~~~
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:990:43: note: passing argument to parameter 'context' here
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:994:43: error: cannot initialize a parameter of type 'int' with an rvalue of type 'nullptr_t'
                       napi_async_context context = nullptr) const;
                                          ^         ~~~~~~~
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:994:43: note: passing argument to parameter 'context' here
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:1016:7: error: unknown type name 'napi_deferred'
      napi_deferred _deferred;
      ^
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:1168:30: error: unknown type name 'napi_async_context'
                             napi_async_context context = nullptr) const;
                             ^
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:1171:30: error: unknown type name 'napi_async_context'
                             napi_async_context context = nullptr) const;
                             ^
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:1175:30: error: unknown type name 'napi_async_context'
                             napi_async_context context = nullptr) const;
                             ^
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:1168:49: error: cannot initialize a parameter of type 'int' with an rvalue of type 'nullptr_t'
                             napi_async_context context = nullptr) const;
                                                ^         ~~~~~~~
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:1168:49: note: passing argument to parameter 'context' here
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:1171:49: error: cannot initialize a parameter of type 'int' with an rvalue of type 'nullptr_t'
                             napi_async_context context = nullptr) const;
                                                ^         ~~~~~~~
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:1171:49: note: passing argument to parameter 'context' here
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:1175:49: error: cannot initialize a parameter of type 'int' with an rvalue of type 'nullptr_t'
                             napi_async_context context = nullptr) const;
                                                ^         ~~~~~~~
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:1175:49: note: passing argument to parameter 'context' here
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:1759:14: error: unknown type name 'napi_async_context'
    operator napi_async_context() const;
             ^
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:1763:5: error: unknown type name 'napi_async_context'
    napi_async_context _context;
    ^
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:2045:20: error: unknown type name 'napi_node_version'
      static const napi_node_version* GetNodeVersion(Env env);
                   ^
In file included from ../lib/mac/src/noble_mac.mm:7:
In file included from ../lib/mac/src/noble_mac.h:3:
In file included from /Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:2051:
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi-inl.h:437:24: error: use of undeclared identifier 'napi_is_promise'
  napi_status status = napi_is_promise(_env, _value, &result);
                       ^
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi-inl.h:448:24: error: use of undeclared identifier 'napi_is_dataview'
  napi_status status = napi_is_dataview(_env, _value, &result);
                       ^
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi-inl.h:535:24: error: use of undeclared identifier 'napi_create_double'
  napi_status status = napi_create_double(env, val, &value);
                       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/binding/lib/mac/src/noble_mac.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/herrjemand/testElectronAPP/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/herrjemand/.nvm/versions/node/v8.16.1/bin/node" "/Users/herrjemand/testElectronAPP/node_modules/.bin/node-gyp" "rebuild" "--target=1.8.8" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /Users/herrjemand/testElectronAPP/node_modules/noble
gyp ERR! node -v v8.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok

Failed with exit code: 1

Error:   CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  LIBTOOL-STATIC Release/nothing.a
  CXX(target) Release/obj.target/binding/lib/mac/src/noble_mac.o
In file included from ../lib/mac/src/noble_mac.mm:7:
In file included from ../lib/mac/src/noble_mac.h:3:
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:987:24: error: unknown type name 'napi_async_context'
                       napi_async_context context = nullptr) const;
                       ^
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:990:24: error: unknown type name 'napi_async_context'
                       napi_async_context context = nullptr) const;
                       ^
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:994:24: error: unknown type name 'napi_async_context'
                       napi_async_context context = nullptr) const;
                       ^
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:987:43: error: cannot initialize a parameter of type 'int' with an rvalue of type 'nullptr_t'
                       napi_async_context context = nullptr) const;
                                          ^         ~~~~~~~
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:987:43: note: passing argument to parameter 'context' here
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:990:43: error: cannot initialize a parameter of type 'int' with an rvalue of type 'nullptr_t'
                       napi_async_context context = nullptr) const;
                                          ^         ~~~~~~~
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:990:43: note: passing argument to parameter 'context' here
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:994:43: error: cannot initialize a parameter of type 'int' with an rvalue of type 'nullptr_t'
                       napi_async_context context = nullptr) const;
                                          ^         ~~~~~~~
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:994:43: note: passing argument to parameter 'context' here
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:1016:7: error: unknown type name 'napi_deferred'
      napi_deferred _deferred;
      ^
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:1168:30: error: unknown type name 'napi_async_context'
                             napi_async_context context = nullptr) const;
                             ^
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:1171:30: error: unknown type name 'napi_async_context'
                             napi_async_context context = nullptr) const;
                             ^
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:1175:30: error: unknown type name 'napi_async_context'
                             napi_async_context context = nullptr) const;
                             ^
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:1168:49: error: cannot initialize a parameter of type 'int' with an rvalue of type 'nullptr_t'
                             napi_async_context context = nullptr) const;
                                                ^         ~~~~~~~
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:1168:49: note: passing argument to parameter 'context' here
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:1171:49: error: cannot initialize a parameter of type 'int' with an rvalue of type 'nullptr_t'
                             napi_async_context context = nullptr) const;
                                                ^         ~~~~~~~
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:1171:49: note: passing argument to parameter 'context' here
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:1175:49: error: cannot initialize a parameter of type 'int' with an rvalue of type 'nullptr_t'
                             napi_async_context context = nullptr) const;
                                                ^         ~~~~~~~
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:1175:49: note: passing argument to parameter 'context' here
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:1759:14: error: unknown type name 'napi_async_context'
    operator napi_async_context() const;
             ^
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:1763:5: error: unknown type name 'napi_async_context'
    napi_async_context _context;
    ^
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:2045:20: error: unknown type name 'napi_node_version'
      static const napi_node_version* GetNodeVersion(Env env);
                   ^
In file included from ../lib/mac/src/noble_mac.mm:7:
In file included from ../lib/mac/src/noble_mac.h:3:
In file included from /Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi.h:2051:
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi-inl.h:437:24: error: use of undeclared identifier 'napi_is_promise'
  napi_status status = napi_is_promise(_env, _value, &result);
                       ^
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi-inl.h:448:24: error: use of undeclared identifier 'napi_is_dataview'
  napi_status status = napi_is_dataview(_env, _value, &result);
                       ^
/Users/herrjemand/testElectronAPP/node_modules/node-addon-api/napi-inl.h:535:24: error: use of undeclared identifier 'napi_create_double'
  napi_status status = napi_create_double(env, val, &value);
                       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/binding/lib/mac/src/noble_mac.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/herrjemand/testElectronAPP/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/herrjemand/.nvm/versions/node/v8.16.1/bin/node" "/Users/herrjemand/testElectronAPP/node_modules/.bin/node-gyp" "rebuild" "--target=1.8.8" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /Users/herrjemand/testElectronAPP/node_modules/noble
gyp ERR! node -v v8.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (/Users/herrjemand/testElectronAPP/node_modules/spawn-rx/lib/src/index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (/Users/herrjemand/testElectronAPP/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.error (/Users/herrjemand/testElectronAPP/node_modules/rxjs/internal/Subscriber.js:156:26)
    at Subscriber._error (/Users/herrjemand/testElectronAPP/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/Users/herrjemand/testElectronAPP/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/Users/herrjemand/testElectronAPP/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/Users/herrjemand/testElectronAPP/node_modules/rxjs/internal/Subscriber.js:72:18)
    at SafeSubscriber._next (/Users/herrjemand/testElectronAPP/node_modules/spawn-rx/lib/src/index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (/Users/herrjemand/testElectronAPP/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/Users/herrjemand/testElectronAPP/node_modules/rxjs/internal/Subscriber.js:143:22)
Connecting process...
Error connecting to Noble API. The error is:  Error: The module '/Users/herrjemand/testElectronAPP/node_modules/noble/lib/mac/native/binding.node'
was compiled against the ABI-stable Node.js API (N-API).
This feature is experimental and must be enabled on the
command-line by adding --napi-modules.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/herrjemand/testElectronAPP/node_modules/noble/lib/mac/bindings.js:4:16)
    at Object.<anonymous> (/Users/herrjemand/testElectronAPP/node_modules/noble/lib/mac/bindings.js:10:3)
ELECTRON VERSION: 1.8.8
NODE VERSION: 8.2.1
```

**Comment by rzr** [comment]
Is 1.8.8 still supported ?

May you consider to use a supported stable release:

https://www.electronjs.org/releases/stable

It looks like there is no LTS:

https://www.electronjs.org/docs/tutorial/about

**Comment by herrjemand** [comment]
@rzr Yeah, the project i am working on was stuck in 1.8.x due to library incompatibility, but after some work i have move all the way to 8.x XD

So thanks! XD

**Comment by rzr** [comment]
Is your project opensource ? If yes may a chapter be added on README file to track use of noble ?

**Comment by herrjemand** [comment]
@rzr Sadly no.

But I can tell that any 1.8.8 has this issue

**Comment by herrjemand** [comment]
@rzr it happens on the rebuild part
