### ISSUE TITLE
Windows build fails with Visual Studio 2019 but succeeds with Visual Studio 2017

### ISSUE THREAD

**Issue by gfrung4** [abandonware/noble#277]
When I pull the current master branch (commit [02bdb84](https://github.com/abandonware/noble/tree/02bdb84fb76d268f14c6b58cf98aede6d463b7d4)) and try to build it, the build succeeds when using Visual Studio 2017, but fails with Visual Studio 2019.

This is surprising to me because it looks like your GitHub [prebuild](https://github.com/abandonware/noble/actions/workflows/prebuild.yml) action is using Visual Studio 2019 and it succeeds.

Specifically, when I build with Visual Studio 2019 (16.11.33027.164) the build fails when building **noble_winrt.cc**:

```
noble-master\lib\win\src\notify_map.h(31,54): error C2064: term does not evaluate to a function taking 1 arguments [noble-master\build\lib\win\binding.vcxproj]
noble-master\lib\win\src\notify_map.h(32,61): error C2064: term does not evaluate to a function taking 1 arguments [noble-master\build\lib\win\binding.vcxproj]
noble-master\lib\win\src\notify_map.h(33,1): error C3536: 'serviceHash': cannot be used before it is initialized [noble-master\build\lib\win\binding.vcxproj]
noble-master\lib\win\src\notify_map.h(34,1): error C3536: 'characteristicHash': cannot be used before it is initialized [noble-master\build\lib\win\binding.vcxproj]
```

This error does not occur when I use Visual Studio 2017 (15.9.33027.88).

Any thoughts on why this is, and why the GitHub [prebuild](https://github.com/abandonware/noble/actions/workflows/prebuild.yml) action succeeds even though it is using Visual Studio 2019?

This isn't a major issue, since I can just build using Visual Studio 2017, but I do wonder why 2019 fails.

**Comment by Nathan-L-Cook** [comment]
Same problem here with VS2019.  It was actually working for me with VS2019 up until recently (probably something in Release 1.9.2-19).

**Comment by rickymohk** [comment]
Getting this issue. I could have use VS2017 but I am using electron-rebuild which complains about path longer than 260 characters so I have to upgrade to VS2019, now I am stuck.

**Comment by rickymohk** [comment]
So the commit fd5e2ad033e02644e9358a03b15d9701485aa4f3 explicitly remove the definition and implementation of `std::hash<winrt:guid>` for VS2019 and after. I don't know this commit's intention but removing the condition seems make it able to build on VS2019.

**Comment by jins-tkomoda** [comment]
Our team found that Windows SDK >=22000 will pass a build with VS2019/2022.
